// <auto-generated />
namespace MOD_17E_PROJETO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Mod17E : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mod17E));
        
        string IMigrationMetadata.Id
        {
            get { return "202303071625434_Mod17E"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
